### ISSUE TITLE
Skipping songs when doing batch mode

### ISSUE THREAD

**Issue by djergo** [MikiraSora/BmsPreviewAudioGenerator#1]
Did a batch on 6601 files, but the program only recognized 5246.

Command line used: BmsPreviewAudioGenerator.exe -batch -path="dir" -start="45%" -end="60%" -save_name="preview.ogg"

Examples of skipped songs:
Agito
flow (LuL Prog Remix)
Fly Again (bms edit)
Circuitry

**Comment by MikiraSora** [comment]
Normally this program only parse/convert bms which file format is `.bms`. ` .bml/.bme/.bmson` will be **ignore** because I'm not sure if these file could work by parser library.
If you want to also parse them, please add a commandl line option `-support_extend_format`

**Comment by djergo** [comment]
Thanks! That seemed to do the trick for the missing files.
