### ISSUE TITLE
Object reference not set to an instance of an object. (bmson convert files)

### ISSUE THREAD

**Issue by estebanxz** [MikiraSora/BmsPreviewAudioGenerator#13]
im trying to use the preview generator to generate preview files for ez2dj bms converts (they are in bmson format) but all fail with the following error:

Object reference not set to an instance of an object.

Heres the full log:
[bmspreview log.txt](https://github.com/user-attachments/files/17693453/bmspreview.log.txt)

NOTE FOR DEV: this convert bmson files cannot be released publicly, but if you are willing to fix this problem, i can privately send you all the files so you can troubleshoot and fix, let me know!

**Comment by MikiraSora** [comment]
If allowed please send some problematic bms to my [email](mailto:MikiraSora0409@126.com)

**Comment by estebanxz** [comment]
> If allowed please send some problematic bms to my [email](mailto:MikiraSora0409@126.com)

Done!

**Comment by MikiraSora** [comment]
try [this](https://github.com/MikiraSora/BmsPreviewAudioGenerator/releases/download/v0.9.9.7/BmsPreviewAudioGenerator.v0.9.9.7.NO_AOT.zip)

**Comment by estebanxz** [comment]
> try [this](https://github.com/MikiraSora/BmsPreviewAudioGenerator/releases/download/v0.9.9.7/BmsPreviewAudioGenerator.v0.9.9.7.NO_AOT.zip)

everything worked fine! all 476 bms generated previews correctly! thank you so much!

**Comment by MikiraSora** [comment]
well there are some problem in NativeAOT building
