### ISSUE TITLE
convert bms to audio from first note, not first measure.

### ISSUE THREAD

**Issue by RaceDriverMIKU** [MikiraSora/BmsPreviewAudioGenerator#3]
Convert bms to audio from first note(audio que?), not first measure.
Hello, this program is awesome, I'm really helped by this program for playing beatoraja.
By the way, I want to make full preview, instead of partial ones, and the problem comes, previews of some of BMS start right after I put a cursor on them, some starts few seconds later.
Open things starts few seconds later via bms editor, the first audio que is placed at 2nd~3rd measure, so preview doesn't start right after I select it.
So if it is possible, it is really appreciate making the feature.
Or cutting feature(start, end parameter) doesn't rely on BMS parsing library, cutting silent from start would be good.

**Comment by MikiraSora** [comment]
https://github.com/MikiraSora/BmsPreviewAudioGenerator/releases/tag/v0.8.7
take a try

**Comment by RaceDriverMIKU** [comment]
So far, it worked as expected.
Previews are played as soon as I put a cursor on it.
Thank you very much.
