### ISSUE TITLE
csbms-parser release

### ISSUE THREAD

**Issue by potchy** [MikiraSora/BmsPreviewAudioGenerator#4]
I noticed the latest release available for download is two commits behind the master branch.
The only remarkable change I found is that Bemusilization was replaced with csbms-parser.
Is there a reason why a new release wasn't made after that change?
Do you think csbms-parser is less reliable?

**Comment by MikiraSora** [comment]
as we all known that csbms-parser is porting project from java project named "jbms-parser"
I had finished porting but there is some bugs to solve and I have no time to debug at that time
So I didnt publish a new release after porting.
for example [this bms](https://manbow.nothing.sh/event/event.cgi?action=More_def&num=253&event=123)
![image](https://user-images.githubusercontent.com/7549173/162588264-af15c194-aa96-4ac1-9920-b60de7083a60.png)


Lately maybe I could refocus this project and debug.

**Comment by MikiraSora** [comment]
done , have a try
https://github.com/MikiraSora/BmsPreviewAudioGenerator/releases/tag/v0.8.8

**Comment by potchy** [comment]
Hey, thank you for the trouble!
Sorry for the super late reply.
