### ISSUE TITLE
#LnType1下的长条key音重复录制问题

### ISSUE THREAD

**Issue by ScelyM** [MikiraSora/BmsPreviewAudioGenerator#5]
在此Preview生成工具中#LnType 1下谱面中的长条会在开头和结尾位置一共播放两次，对应的轨道为（以下简写掉小节号）51/52/53/54/55/56/58/59/61/62/63/64/65/66/68/69。

![LnType1 示例](https://user-images.githubusercontent.com/60597533/154437220-1b5278e4-69c8-43b4-9ca7-bac81e189e54.png)

不同于#LnObj xx定义是写在11/12/13等游玩轨道上的note并且一般不会有对应的key音定义，#LnType 1的作用方式是使用另外的轨道定义来判定LN，也就是会输出上面的代码行。根据我的推断，此工具应该没有判断定义具体作用的功能，也就是在这种情况下，note对应的key音将会在LN开始和结束的位置重复播放。

**在我对BMS格式的理解下，建议您的解决方式为：在这些轨道下每两个相同定义只读取第一个定义的位置播放key音。**

另外我读取了隐藏note和地雷note的定义轨，为
（hidden notes）31/32/33/34/35/36/38/39/41/42/43/44/45/46/48/49
（mine notes）D1/D2/D3/D4/D5/D6/D8/D9/E1/E2/E3/E4/E5/E6/E8/E9
希望您能在后续更新中屏蔽这些轨道定义。

**Comment by MikiraSora** [comment]
来一份bms文件夹

另外其实我不怎么会看bms谱面文件格式的 😢

**Comment by MikiraSora** [comment]
试试看这个？
https://github.com/MikiraSora/BmsPreviewAudioGenerator/releases/tag/v0.8.8
